# Generated by Django 4.0.1 on 2022-01-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_image_profile_capacity_of_the_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='capacity_of_the_car',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='license_plate_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spacial_request',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vehicle_type_registered',
            field=models.CharField(default='', max_length=200),
        ),
    ]
