# Generated by Django 4.0.1 on 2022-01-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_driver_alter_profile_capacity_of_the_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
