# Generated by Django 4.0.1 on 2022-01-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_is_driver_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='capacity_of_the_car',
            field=models.IntegerField(default=''),
        ),
    ]
