# Generated by Django 4.0.1 on 2022-01-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driveruserform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(max_length=200)),
                ('vehicle_type_registered', models.CharField(max_length=200)),
                ('license_plate_number', models.CharField(max_length=200)),
                ('capacity_of_the_car', models.CharField(max_length=2)),
            ],
        ),
    ]
