# Generated by Django 4.0.1 on 2022-01-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='driveruserform',
        ),
    ]
